modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "examplemod"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
A fork of PatchouliResourcePatch.  
Make patchouli books can be override by resource packs. Not include book.json.Need to work with existing /data/ books. 
Will try to load from assets first. Support localization.
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.66,)"
ordering = "AFTER"
side = "BOTH"