modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "CC-BY-NC-SA 4.0"

[[mods]]
modId = "archprp"
version = "${version}"
displayName = "PatchouliResourcePatch-Arch"
credits="kappa-maintainer"
authors = "TexTrue, LocalizedCNMC"
description = '''
A fork of PatchouliResourcePatch.  
Make patchouli books can be override by resource packs. Not include book.json.Need to work with existing /data/ books. 
Will try to load from assets first. Support localization.
'''
logoFile = "icon.png"

[[dependencies.archprp]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archprp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,1.17.1]"
ordering = "NONE"
side = "BOTH"